### ISSUE TITLE
error: OOPS; losing 1435271168 edges beyond MAXEDGES=131072

### ISSUE THREAD

**Issue by huglester** [Zwilla/BitCaine5_aeternity_miner#8]
$ ./cuda29 -r 17
OOPS; losing 1435271168 edges beyond MAXEDGES=131072
OOPS; losing 1435271168 edges beyond MAXEDGES=131072
OOPS; losing 1435271168 edges beyond MAXEDGES=131072
OOPS; losing 1435271168 edges beyond MAXEDGES=131072
OOPS; losing 1435271168 edges beyond MAXEDGES=131072
OOPS; losing 1435271168 edges beyond MAXEDGES=131072
OOPS; losing 1435271168 edges beyond MAXEDGES=131072
OOPS; losing 1435271168 edges beyond MAXEDGES=131072
OOPS; losing 1435271168 edges beyond MAXEDGES=131072
OOPS; losing 1435271168 edges beyond MAXEDGES=131072
OOPS; losing 1435271168 edges beyond MAXEDGES=131072
OOPS; losing 1435271168 edges beyond MAXEDGES=131072
OOPS; losing 1435271168 edges beyond MAXEDGES=131072
OOPS; losing 1435271168 edges beyond MAXEDGES=131072
OOPS; losing 1435271168 edges beyond MAXEDGES=131072
OOPS; losing 1435271168 edges beyond MAXEDGES=131072
OOPS; losing 1435271168 edges beyond MAXEDGES=131072
0 total solutions of 17 nonces

- what this error could mean?

thank you (1080ti)

**Comment by Zwilla** [comment]
you are using an old buggy software

**Comment by huglester** [comment]
This is strange. Its ubuntu 16.04...

**Comment by huglester** [comment]
Strmge is that on other ubuntu 16.04 it works for me.

**Comment by Zwilla** [comment]
There is something wrong with the edges, so if you use not the default settings. Have you tried a binary from here?

**Comment by huglester** [comment]
I have taken precompiled binary, for 1080 models. Took from github
on one rig (16.04) ir works, on other I get these messages...
